development:
  foursquare_key: '2C1UOPUG3PTENXBFETNDWRJQDJ4V12ZGPYQ1O2DCUTIWPUYP'
  foursquare_secret: 'JAJLKPKO4BS2DR5ZZJ3L5XRXZE2DYCHDEASLMAPM0LDZN1GZ'

production:
  foursquare_key: '2C1UOPUG3PTENXBFETNDWRJQDJ4V12ZGPYQ1O2DCUTIWPUYP'
  foursquare_secret: 'JAJLKPKO4BS2DR5ZZJ3L5XRXZE2DYCHDEASLMAPM0LDZN1GZ'